### ISSUE TITLE
why escape backslashes?

### ISSUE THREAD

**Issue by ngbusca** [opawg/user-agents#26]
It is confusing as to why backslashes `\` are to be escaped. For example, the regexp `^AppleCoreMedia/1\\..*iPod` doesn't match `AppleCoreMedia/1.0.0.16G114 (iPod touch; U; CPU OS 12_4_2 like Mac OS X; en_us)` (this is a user-agent/example pair from the provided json).

The requirement of escaping backslashes forces the user to de-escape them before testing the regexp. Is this the desired usage?

**Comment by mkody** [comment]
We need the dot to be escaped for the regex, so that the final regexp is `^AppleCoreMedia/1\..*iPod`.  
But since the data is in a JSON/YAML file, we need to escape the \ or the JSON/YAML parser will think we're escaping the dot and then we end up with `^AppleCoreMedia/1..*iPod` which is not intended.

**Comment by ngbusca** [comment]
makes sense, thanks!
