### ISSUE TITLE
Filtering Apple Podcasts app watchOS user agent

### ISSUE THREAD

**Issue by jamesfoster85** [opawg/user-agents#59]
We are working on implementing IAB's guidance to filter out downloads from Apple Podcasts app watchOS user agent documented here: https://iabtechlab.com/blog/apple-watch-os-podcast-filtering-guidance

We were hoping to match something like `app == "Apple Podcasts" && os = "watchos".  As of commit https://github.com/opawg/user-agents/commit/4ac49c5587e0fb00dea8e86d7605772a23ee6e98 though it seems this won't be possible and there does not appear to be a definitive way using the OPAWG list to satisfy the IAB requirement.  It allows identifying the watchos but not the Apple Podcasts app specifically.

I'm wondering if there is a more granular regex that would work or do you think this is beyond what is possible with user agents alone, at least at present?

**Comment by jamescridland** [comment]
Hi, James!

The commit says - correctly - that AppleCoreMedia is not Apple Podcasts. It is a variety of things: I should see if I can go through some recent data I've worked on and give an authoritative answer on how many AppleCoreMedia agents are Apple Podcasts.

Since AppleCoreMedia is just the library most apps use to "stream" (aka progressive download), it's not suitable for spotting Apple Podcasts.

But - AppleCoreMedia isn't normally used for downloads, just "streams". If you are "streaming" from an Apple Watch, that looks to me like a valid play, and one that shouldn't be removed? Comments?

**Comment by jamesfoster85** [comment]
The IAB guidance only says that "Apple Watch devices enact an inherent behavior that triggers non-user initiated podcast downloads" but they leave it open how one would discern that behavior at the level of server logs.  But your point about "streaming" is a good one: it seems unlikely that such "non-user initiated podcast downloads" would use that particular library/identify themselves with that user agent.

**Comment by tomrossi7** [comment]
I'm looking through millions of our downloads and having a hard time differentiating duplicate/legitimate watchOS downloads. In most cases, I'm only seeing one download?

**Comment by jamescridland** [comment]
In the Slack group - james@crid.land for an invite if you need one - the discussion leans towards:

1. Add all "watchOS" activity to a block-list.
2. Then, add the legitimate watchOS downloads, which are specific apps, to an allow-list.

I'd welcome any real-world experience.
